language: node_js
os: linux
node_js:
- lts/*
install:
- yarn install
script:
- yarn build
deploy:
  provider: pages
  edge: true
  local_dir: docs/.vuepress/dist/
  token:
    secure: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
